/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_appsync_graphqlEndpoint": "https://7w7n46nf75bvxhhmtuywjnnqmu.appsync-api.eu-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-2impwntkfjet3b4en4sjeukl5y",
    "aws_cognito_identity_pool_id": "eu-west-2:95a94541-aab1-41ae-9b42-279ee3254882",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_wKxCdz1VB",
    "aws_user_pools_web_client_id": "5o5n8rneeioistg4f0ueiofbgi",
    "oauth": {
        "domain": "nextjsamplifyappd27176af-d27176af-dev.auth.eu-west-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://googles.es/",
        "redirectSignOut": "https://google.es/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
